spring:
  profiles:
    active: dev # 修改环境配置文件

  # mybatis配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 5.x版本驱动 8.x版本的驱动为com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/float?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1234567

mybatis:
  type-aliases-package: com.fsyume.eneity
  mapper-locations: classpath:mapper/*.xml